### ISSUE TITLE
loading CSV with different delimiter

### ISSUE THREAD

**Issue by kambala-decapitator** [little-brother/odbc-wlx#1]
I already checked https://github.com/little-brother/odbc-wlx/wiki#csv but it's still unclear to me.

I have a folder with csv files, added `schema.ini` to it with contents:

```
[default]
Format=Delimited(TAB)
```

but the table still looks incorrect.

Also tried placing this file in `%APPDATA%\Roaming\GHISLER` and restarting TC, no effect either.

**Comment by little-brother** [comment]
Use `Format=TabDelimited` instead `Delimited(TAB)`.
Soon csv-support will be removed from this plugin by changing detection string. 
I recommend to use [csvtab](https://github.com/little-brother/csvtab-wlx).
P.S. I hope to update all plugins within two-three days.

**Comment by kambala-decapitator** [comment]
thanks for the help!

changing to `TabDelimited` still had no effect, but csvtab works fine.
