### ISSUE TITLE
Bug Report：Error 42000

### ISSUE THREAD

**Issue by tyf2018** [little-brother/odbc-wlx#2]
Report Error：
![image](https://github.com/little-brother/odbc-wlx/assets/56342788/319283aa-9585-4a2d-be32-82e1411208a5)

This is test file
[text.xlsx](https://github.com/little-brother/odbc-wlx/files/13255594/text.xlsx)

Best regards.

**Comment by little-brother** [comment]
Thanks for the report. Fixed.
