### ISSUE TITLE
Would you consider supporting table files in the et format?

### ISSUE THREAD

**Issue by tyf2018** [little-brother/odbc-wlx#3]
Would you consider supporting table files in the et format?

 like this：
[test.zip](https://github.com/little-brother/odbc-wlx/files/13256781/test.zip)

Best regards.

**Comment by little-brother** [comment]
The plugin uses ODBC drivers to obtain data from sources. I did an quick search and there is no such thing as ODBC for `et` or for `WPS Office`. Hence, no chance for support `et`.

**Comment by tyf2018** [comment]
> Hence, no chance for support `et`.

Although a little regrettable, thank you for your answer.
